<?php

namespace AppBundle\Repository;

/**
 * AgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $agent
     */
    public function findMyAgent($agentsId)
    {
        return $this->createQueryBuilder('agent')
            ->where('agent.id  IN (:agentsId)')
            ->setParameter('agentsId', $agentsId)
            ->getQuery()
            ->getResult()
            ;
    }

}
