<?php

namespace AppBundle\Repository;

/**
 * CodePlanningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodePlanningRepository extends \Doctrine\ORM\EntityRepository
{
}
