<?php

namespace AppBundle\Repository;

/**
 * HistoryChangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryChangeRepository extends \Doctrine\ORM\EntityRepository
{
}
