<?php

namespace AppBundle\Repository;

/**
 * PostedAgentTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostedAgentTeamRepository extends \Doctrine\ORM\EntityRepository
{
}
