<?php

namespace AppBundle\Repository;

/**
 * RegulatoryConstraintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegulatoryConstraintRepository extends \Doctrine\ORM\EntityRepository
{
}
